# In accounts/urls.py (or events/urls.py)
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EventViewSet, TicketViewSet  # Import other views as needed

router = DefaultRouter()
router.register(r"events", EventViewSet)

urlpatterns = [
    path("", include(router.urls)),
    # Nested URLs for Tickets under Events
    path(
        "events/<int:event_pk>/tickets/",
        TicketViewSet.as_view({"get": "list", "post": "create"}),
        name="event_tickets_list",
    ),
    path(
        "events/<int:event_pk>/tickets/<int:pk>/",
        TicketViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="event_tickets_detail",
    ),  # Include the urls generated by the router
]
